package:
  name: cartopy
  version: "0.11.2"
source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.11.2

requirements:
  build:
    - python
    - six
    - numpy
    - cython
    - proj4
    - shapely
    - owslib # (only needed for test dependency)
  run:
    - python
    - six
    - mock
    - nose
    - pil
    - owslib
    - numpy
    - proj4
    - shapely
    - scipy
    - pyshp
    - matplotlib

test:
  commands:
    - nosetests cartopy --with-doctest -sv

  imports:
    - cartopy
    - cartopy.mpl.geoaxes

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

